In [9]:


import pandas as pd
from sklearn.model_selection import train_test_split
import html, re

In [21]:
re1 = re.compile(r'  +')

def fixup(x, title=False):
    x = x.replace('#39;', "'").replace('amp;', '&').replace('#146;', "'").replace(
        'nbsp;', ' ').replace('#36;', '$').replace('\\n', "\n").replace('quot;', "'").replace(
        '<br />', "\n").replace('\\"', '"').replace('<unk>','u_n').replace(' @.@ ','.').replace(
        ' @-@ ','-').replace('\\', ' \\ ')
    if title:
        x = x.replace('\n', '').replace('\t', '')
    return re1.sub(' ', html.unescape(x))

def concat_text_title(row):
    separator = ' ' if row['title'].endswith('.') else '. '
    return row['title'] + separator + row['text']

In [34]:
news_df = pd.read_csv('/media/discoD/Mestrado/FASAM/df_train.csv')
news_df['title'] = news_df.apply(lambda row: fixup(row['title'], title=True), axis=1)
news_df['text'] = news_df.apply(lambda row: fixup(row['text'], title=False), axis=1)
news_df['text'] = news_df.apply(lambda row: concat_text_title(row), axis=1)
news_df['label'] = news_df['category']
del news_df['category']
del news_df['title']
news_df = news_df.reindex(columns = ['label','text'])
news_df.to_json('/media/discoD/Mestrado/FASAM/df_train.jsonl', orient='records', lines=True)
news_df

                   label                                               text
0                 comida  Casa da Barra Funda tem clima roceiro e receit...
1               educacao  Professores de SP decidem manter greve; grupo ...
2     empreendedorsocial  Em segunda edição, concurso paga R$ 35 mil par...
3       equilibrioesaude  Usar maconha por anos não faz tão mal para a s...
4                ciencia  Baleia-azul percorre 5.200 km e revela a cient...
5     empreendedorsocial  Líderes inovadores se reunem em rede para comp...
6                turismo  Conheça Pandora, atração milionária da Disney ...
7     empreendedorsocial  Fiesp organiza quarta edição de maratona hacke...
8                turismo  Praia do Forte mistura natureza com resorts es...
9                turismo  App de agência avisa quando visto e passaporte...
10               turismo  App de caronas para viagens não teme comparaçõ...
11             sobretudo  Veja quais são os tipos de veículos que precis...
12               ciencia  Rica em fósseis de dinos, Uberaba deve ter geo...
13                   tec  Yahoo! tem prejuízo de US$ 492 milhões no 2º t...
14    empreendedorsocial  Bazar beneficente tem comida típica síria feit...
15               turismo  5 lugares para voar de balão no Brasil. As pos...
16                   tec  Loja de aplicativos do Google oferece opção pr...
17               turismo  Paris proibirá circulação de carros em trecho ...
18                   tec  Chinesa ZTE diz que lucro dobrou no ano passad...
19                comida  Gwyneth Paltrow desiste do desafio de passar 7...
20              educacao  Tema de redação do Enem vazou antes do início ...
21              educacao  Planejamento evita aperto no orçamento na hora...
22                   tec  Nas mensagens, GIFs valem pelo menos mil palav...
23    empreendedorsocial  ONG arrecada material escolar a 7 mil crianças...
24              educacao  Educação média não consegue formar quadros téc...
25             sobretudo  Artista plástica ensina a fazer suportes para ...
26                   tec  Confira o kit de decoração de unhas tetris e o...
27    empreendedorsocial  Ciclo Brilhante quer inspirar 100 mil brasilei...
28              ambiente  Trump diz estar com 'mente aberta' em relação ...
29              educacao  Temida, química exige relações com o cotidiano...
...                  ...                                                ...
7864             ciencia  Pica-paus se arriscam para manter higiene do n...
7865                 tec  Programa deixa o novo Windows 10 com cara de W...
7866             turismo  Brasileiros dão 'jeitinho' para baratear ida a...
7867             turismo  Pouco conhecida, ilha de Santa Lúcia tem paisa...
7868           sobretudo  Criado nos EUA, conceito de MBA foi 'tropicali...
7869           sobretudo  É preciso abrir mão de espaço e localização na...
7870    equilibrioesaude  Não usar azeite para fritar? Veja regras culin...
7871                 tec  Que navegador para celular usar? Os pontos pos...
7872  empreendedorsocial  FGV Eaesp lança mestrado profissional de suste...
7873            educacao  Justiça realiza audiência de conciliação entre...
7874  empreendedorsocial  Empreendedores sociais fazem da cidadania o fo...
7875              comida  Mudança no clima leva marca francesa a produzi...
7876                 tec  Aventura política na Nova Zelândia afeta reput...
7877            ambiente  Imagem de satélite mostra movimento de iceberg...
7878           sobretudo  Saiba como limpar a lavadora de roupas da form...
7879    equilibrioesaude  Ansiedade matemática de pais contagia filhos. ...
7880            educacao  MEC vai receber até dia 17 sugestões de mudanç...
7881                 tec  Apple conquista patente para aparelho de reali...
7882              comida  Veg: Curitiba terá festival com sete tipos de ...
7883             turismo  Quanto custa a comida que as companhias aéreas...
7884  empreendedorsocial  'Amo o lixão', afirma catadora após trocar o l...
7885    equilibrioesaude  Tenho uma bolha na gengiva. O que faço, devo m...
7886             ciencia  Planetas fora do Sistema Solar são batizados e...
7887    equilibrioesaude  Entrada do zika no Brasil pode ter sido na Cop...
7888              comida  Veg: Comidas vegetarianas para uma viagem de b...
7889             ciencia  Mensageiro Sideral: Uma olhada noutros planeta...
7890            educacao  Sem verba, MEC pode suspender Pronatec. A cont...
7891            educacao  Deputado do PT agride PM durante invasão na As...
7892            educacao  Governo avalia reduzir a 10% desconto automáti...
7893  empreendedorsocial  Calouro vira CEO de rede de escolas de inglês ...

[7894 rows x 2 columns]

In [37]:
news_df = pd.read_csv('/media/discoD/Mestrado/FASAM/df_train.csv')
news_df['text'] = news_df.apply(lambda row: fixup(row['title'], title=True), axis=1)
news_df['label'] = news_df['category']
del news_df['category']
del news_df['title']
news_df = news_df.reindex(columns = ['label','text'])
news_df.to_json('/media/discoD/Mestrado/FASAM/df_train_title.jsonl', orient='records', lines=True)
news_df

                   label                                               text
0                 comida  Casa da Barra Funda tem clima roceiro e receit...
1               educacao  Professores de SP decidem manter greve; grupo ...
2     empreendedorsocial  Em segunda edição, concurso paga R$ 35 mil par...
3       equilibrioesaude  Usar maconha por anos não faz tão mal para a s...
4                ciencia  Baleia-azul percorre 5.200 km e revela a cient...
5     empreendedorsocial  Líderes inovadores se reunem em rede para comp...
6                turismo  Conheça Pandora, atração milionária da Disney ...
7     empreendedorsocial    Fiesp organiza quarta edição de maratona hacker
8                turismo  Praia do Forte mistura natureza com resorts es...
9                turismo  App de agência avisa quando visto e passaporte...
10               turismo  App de caronas para viagens não teme comparaçõ...
11             sobretudo  Veja quais são os tipos de veículos que precis...
12               ciencia  Rica em fósseis de dinos, Uberaba deve ter geo...
13                   tec  Yahoo! tem prejuízo de US$ 492 milhões no 2º t...
14    empreendedorsocial  Bazar beneficente tem comida típica síria feit...
15               turismo             5 lugares para voar de balão no Brasil
16                   tec  Loja de aplicativos do Google oferece opção pr...
17               turismo  Paris proibirá circulação de carros em trecho ...
18                   tec    Chinesa ZTE diz que lucro dobrou no ano passado
19                comida  Gwyneth Paltrow desiste do desafio de passar 7...
20              educacao  Tema de redação do Enem vazou antes do início ...
21              educacao  Planejamento evita aperto no orçamento na hora...
22                   tec  Nas mensagens, GIFs valem pelo menos mil palavras
23    empreendedorsocial  ONG arrecada material escolar a 7 mil crianças...
24              educacao  Educação média não consegue formar quadros téc...
25             sobretudo  Artista plástica ensina a fazer suportes para ...
26                   tec  Confira o kit de decoração de unhas tetris e o...
27    empreendedorsocial  Ciclo Brilhante quer inspirar 100 mil brasilei...
28              ambiente  Trump diz estar com 'mente aberta' em relação ...
29              educacao  Temida, química exige relações com o cotidiano...
...                  ...                                                ...
7864             ciencia  Pica-paus se arriscam para manter higiene do n...
7865                 tec  Programa deixa o novo Windows 10 com cara de W...
7866             turismo  Brasileiros dão 'jeitinho' para baratear ida a...
7867             turismo  Pouco conhecida, ilha de Santa Lúcia tem paisa...
7868           sobretudo  Criado nos EUA, conceito de MBA foi 'tropicali...
7869           sobretudo  É preciso abrir mão de espaço e localização na...
7870    equilibrioesaude  Não usar azeite para fritar? Veja regras culin...
7871                 tec  Que navegador para celular usar? Os pontos pos...
7872  empreendedorsocial  FGV Eaesp lança mestrado profissional de suste...
7873            educacao  Justiça realiza audiência de conciliação entre...
7874  empreendedorsocial  Empreendedores sociais fazem da cidadania o fo...
7875              comida  Mudança no clima leva marca francesa a produzi...
7876                 tec  Aventura política na Nova Zelândia afeta reput...
7877            ambiente  Imagem de satélite mostra movimento de iceberg...
7878           sobretudo  Saiba como limpar a lavadora de roupas da form...
7879    equilibrioesaude       Ansiedade matemática de pais contagia filhos
7880            educacao  MEC vai receber até dia 17 sugestões de mudanç...
7881                 tec  Apple conquista patente para aparelho de reali...
7882              comida  Veg: Curitiba terá festival com sete tipos de ...
7883             turismo  Quanto custa a comida que as companhias aéreas...
7884  empreendedorsocial  'Amo o lixão', afirma catadora após trocar o l...
7885    equilibrioesaude  Tenho uma bolha na gengiva. O que faço, devo m...
7886             ciencia  Planetas fora do Sistema Solar são batizados e...
7887    equilibrioesaude  Entrada do zika no Brasil pode ter sido na Cop...
7888              comida  Veg: Comidas vegetarianas para uma viagem de b...
7889             ciencia    Mensageiro Sideral: Uma olhada noutros planetas
7890            educacao             Sem verba, MEC pode suspender Pronatec
7891            educacao  Deputado do PT agride PM durante invasão na As...
7892            educacao  Governo avalia reduzir a 10% desconto automáti...
7893  empreendedorsocial  Calouro vira CEO de rede de escolas de inglês ...

[7894 rows x 2 columns]

In [38]:
news_df = pd.read_csv('/media/discoD/Mestrado/FASAM/df_valid.csv')
news_df

,Unnamed: 0,title,text
0,0,"Vitrine de Dilma, Pronatec terá orçamento 65% ...","Em compasso de espera, o baiano Leonardo Souza..."
1,1,"Por direitos autorais e publicidade, 'youtuber...",Fosse o segmento de vídeos on-line um tribunal...
2,2,Rótulos de alimentos terão que alertar sobre l...,Rótulos de todos os alimentos e bebidas indust...
3,3,Sociedade britânica de compositores processa S...,"A PRS for Music, maior cooperativa de direitos..."
4,4,"Por Fies, aluna madruga na porta da FMU, mas s...","Rafhaela Melo, 19, aluna do curso de economia ..."
5,5,Cientistas aguardam nascimento raro de 'dragõe...,Em uma caverna visitada por um milhão de turis...
6,6,Aplicativo mostra quem está no mesmo voo que você,"O ""Turismo"" prepara uma seleção de dicas, novi..."
7,7,\n\t\tPesquisas indicam que sono na direção po...,EVERTON LOPES BATISTA DE SÃO PAULO O arquitet...
8,8,Brasil lançará missão à Lua até 2020 para estu...,Um time de cientistas de instituições de ponta...
9,9,Cientistas testam vacina contra colesterol e d...,Depois de testes bem-sucedidos com camundongos...
10,10,Farol da Torre Eiffel é desligado para manutenção,"Pela primeira vez desde que começou a operar, ..."
11,11,Finalistas do Empreendedor Social terão mentor...,Pioneira na disseminação e fomento de negócios...
12,12,Eventos marcam comemorações do aniversário de SP,A programação pelo aniversário de 461 anos de ...
13,13,Folha realiza fórum sobre saúde em tempo de re...,Nos dias 14 e 15 de junho (terça e quarta-feir...
14,14,Por que o 'MasterChef' bateu recordes no Twitter?,"O vencedor da segunda temporada do ""MasterChef..."
15,15,Complexo gastronômico é inaugurado no Recife; ...,"O ""Turismo"" prepara uma seleção de dicas, novi..."
16,16,"Empresa de presidente do Twitter, Square vai e...","A Square, empresa de pagamento por celular cof..."
17,17,\n\t\tLojas e restaurantes testemunham as tran...,SANDRO MACEDO COLABORAÇÃO PARA A FOLHA PLAS...
18,18,Fotógrafo registra cânions gaúchos em preto e ...,Na fronteira entre os Estados de Rio Grande do...
19,19,Fórum discute inclusão teatral com foco em pro...,Em um espaço para reflexão e troca de experiên...
20,20,Artista cria em meio ao inferno da favela: 'Co...,"Jandir Leite Moreira, 44, nasceu e cresceu no ..."
21,21,Casal fotografa cenas e paisagens pelo mundo q...,"Em dez anos, o casal de jornalistas Renato Wei..."
22,22,Fóssil de mandíbula leva à descoberta de bicho...,"Se ainda estivesse vivo, o réptil de 80 milhõe..."
23,23,Food truck do Mocotó venderá dadinhos de tapio...,"O food truck do restaurante Mocotó, inaugurado..."
24,24,Cientistas comparam ondas cerebrais e algoritmos,Muitos cientistas resistem à ideia de que o cé...
25,25,Música mais antiga criada por computador é res...,Pesquisadores acabam de restaurar a mais antig...
26,26,Lua de Júpiter vira aposta de cientistas na bu...,Depois de duas décadas de preparo e frustraçõe...
27,27,\n\t\tProjeto transforma quarto em área multiú...,DE SÃO PAULO O morador desse apartamento de 9...
28,28,Especialistas estimam em US$ 3 tri transição p...,O investimento necessário para a transição a u...
29,29,Área de reserva para mineração é igual a 4 ano...,O Ministério Público Federal (MPF) emitiu uma ...
...,...,...,...
4221,4221,Fenômeno El Niño de 2015 deve ser um dos mais ...,Especialistas alertam que o fenômeno climático...
4222,4222,Mensageiro Sideral: Treinamento em jornalismo ...,Sempre quis trabalhar com divulgação científic...
4223,4223,\n\t\tPirituba concentra condomínios gigantesc...,JUSSARA SOARES COLABORAÇÃO PARA A FOLHA Os ci...
4224,4224,\n\t\tCarreira de direito ganha mais fama e in...,JULLIANE SILVEIRA COLABORAÇÃO PARA A FOLHA As...
4225,4225,Um reconhecimento à causa,O bom de ser reconhecido com o Wildlife Conser...
4226,4226,Refazer provas antigas do Enem pode ajudar na ...,"Daqui a dois dias mais de 8,6 milhões de estud..."
4227,4227,Negócios sociais voltados à primeira infância ...,"O artista plástico Roni Hirsch, 37, criou, no ..."
4228,4228,\n\t\tCarros que chegam em 2017 valorizam espa...,EDUARDO SODRÉ COLUNISTA DA FOLHA O ano de 201...
4229,4229,Proposta pode acabar com despacho gratuito de ...,"Pagar por malas despachadas, não receber ajuda..."
4230,4230,Cai para 57 o número de escolas ocupadas em Sã...,O número de escolas ocupadas contra a reorgani...
4231,4231,Brasileiro é eleito melhor jogador de videogam...,"O brasileiro Marcelo ""Coldzera"" David, 21, jog..."
4232,4232,"Em um ano na Microsoft, executivo mudou jeito ...","A Microsoft promoveu, na quarta-feira passada ..."
4233,4233,Artemisia seleciona negócios de impacto para p...,"A Artemisia, parceira do Prêmio Empreendedor S..."
4234,4234,"Após reclamações, LinkedIn diminui número de e...",Um dos principais problemas para os usuários d...
4235,4235,Fumar no inverno é pior para a saúde?,Sou fumante e noto que durante o inverno é mai...
4236,4236,Consumo de cereais integrais pode aumentar lon...,Uma dieta que inclui três porções diárias de c...
4237,4237,"\n\t\tPróxima do metrô, Vila Guilherme cresce ...",DOUGLAS GAVRAS COLABORAÇÃO PARA A FOLHA Entre...
4238,4238,Microsoft vai abandonar marca Internet Explorer,A Microsoft confirmou que o seu novo navegador...
4239,4239,OMS comemora grandes avanços na luta contra do...,A OMS (Organização Mundial da Saúde) comemorou...
4240,4240,Modelo de financiamento estudantil também é de...,"Como o Brasil, que teve seu programa oficial c..."
4241,4241,Queda na cotação do euro estimula compra da mo...,Os turistas que vão viajar para a Europa nos p...
4242,4242,Governo promete pagar a professores meses desc...,A Secretaria de Educação do Estado de São Paul...
4243,4243,Astrônomos da USP tiram dinheiro do próprio bo...,"Após corte de cerca de 80% de recursos, entre ..."
4244,4244,Venda de PCs despencou 38% no segundo trimestr...,A comercialização de computadores pessoais con...
4245,4245,Azul do mar se encontra com paisagem do desert...,Um jipe antigo. Colocar a primeira marcha é du...
4246,4246,Barbie grava conversa e 'vira' espiã da Aleman...,"A boneca nem chegou às lojas, mas já foi apeli..."
4247,4247,Crescimento no serviço de nuvem não evita qued...,"A Microsoft reportou queda de 6,6% na receita ..."
4248,4248,O revolucionário projeto de viagem interestela...,O físico Stephen Hawking anunciou apoio a um p...
4249,4249,Chef suíço que se suicidou pode ter sido vítim...,O chef suíço Benoit Violier –cuja morte chocou...
4250,4250,Humoristas satirizam comportamento de brasilei...,O grupo de humoristas norte-americano The Flor...

In [51]:
news_df = pd.read_csv('/media/discoD/Mestrado/FASAM/df_valid.csv')
print(len(news_df))

4251

In [49]:
news_df['text'] = news_df.apply(lambda row: fixup(row['title'], title=True), axis=1)
del news_df['title']
news_df.columns = ['index', 'text']
news_df.to_json('/media/discoD/Mestrado/FASAM/df_valid_title.jsonl', orient='records', lines=True)
news_df

      index                                               text
0         0  Vitrine de Dilma, Pronatec terá orçamento 65% ...
1         1  Por direitos autorais e publicidade, 'youtuber...
2         2  Rótulos de alimentos terão que alertar sobre l...
3         3  Sociedade britânica de compositores processa S...
4         4  Por Fies, aluna madruga na porta da FMU, mas s...
5         5  Cientistas aguardam nascimento raro de 'dragõe...
6         6  Aplicativo mostra quem está no mesmo voo que você
7         7  Pesquisas indicam que sono na direção pode ser...
8         8  Brasil lançará missão à Lua até 2020 para estu...
9         9  Cientistas testam vacina contra colesterol e d...
10       10  Farol da Torre Eiffel é desligado para manutenção
11       11  Finalistas do Empreendedor Social terão mentor...
12       12   Eventos marcam comemorações do aniversário de SP
13       13  Folha realiza fórum sobre saúde em tempo de re...
14       14  Por que o 'MasterChef' bateu recordes no Twitter?
15       15  Complexo gastronômico é inaugurado no Recife; ...
16       16  Empresa de presidente do Twitter, Square vai e...
17       17  Lojas e restaurantes testemunham as transforma...
18       18  Fotógrafo registra cânions gaúchos em preto e ...
19       19  Fórum discute inclusão teatral com foco em pro...
20       20  Artista cria em meio ao inferno da favela: 'Co...
21       21  Casal fotografa cenas e paisagens pelo mundo q...
22       22  Fóssil de mandíbula leva à descoberta de bicho...
23       23  Food truck do Mocotó venderá dadinhos de tapio...
24       24   Cientistas comparam ondas cerebrais e algoritmos
25       25  Música mais antiga criada por computador é res...
26       26  Lua de Júpiter vira aposta de cientistas na bu...
27       27  Projeto transforma quarto em área multiúso e t...
28       28  Especialistas estimam em US$ 3 tri transição p...
29       29  Área de reserva para mineração é igual a 4 ano...
...     ...                                                ...
4221   4221  Fenômeno El Niño de 2015 deve ser um dos mais ...
4222   4222  Mensageiro Sideral: Treinamento em jornalismo ...
4223   4223  Pirituba concentra condomínios gigantescos apó...
4224   4224  Carreira de direito ganha mais fama e interess...
4225   4225                          Um reconhecimento à causa
4226   4226  Refazer provas antigas do Enem pode ajudar na ...
4227   4227  Negócios sociais voltados à primeira infância ...
4228   4228  Carros que chegam em 2017 valorizam espaço int...
4229   4229  Proposta pode acabar com despacho gratuito de ...
4230   4230  Cai para 57 o número de escolas ocupadas em Sã...
4231   4231  Brasileiro é eleito melhor jogador de videogam...
4232   4232  Em um ano na Microsoft, executivo mudou jeito ...
4233   4233  Artemisia seleciona negócios de impacto para p...
4234   4234  Após reclamações, LinkedIn diminui número de e...
4235   4235              Fumar no inverno é pior para a saúde?
4236   4236  Consumo de cereais integrais pode aumentar lon...
4237   4237  Próxima do metrô, Vila Guilherme cresce ao lad...
4238   4238    Microsoft vai abandonar marca Internet Explorer
4239   4239  OMS comemora grandes avanços na luta contra do...
4240   4240  Modelo de financiamento estudantil também é de...
4241   4241  Queda na cotação do euro estimula compra da mo...
4242   4242  Governo promete pagar a professores meses desc...
4243   4243  Astrônomos da USP tiram dinheiro do próprio bo...
4244   4244  Venda de PCs despencou 38% no segundo trimestr...
4245   4245  Azul do mar se encontra com paisagem do desert...
4246   4246  Barbie grava conversa e 'vira' espiã da Aleman...
4247   4247  Crescimento no serviço de nuvem não evita qued...
4248   4248  O revolucionário projeto de viagem interestela...
4249   4249  Chef suíço que se suicidou pode ter sido vítim...
4250   4250  Humoristas satirizam comportamento de brasilei...

[4251 rows x 2 columns]

In [53]:
news_df = pd.read_csv('/media/discoD/Mestrado/FASAM/df_valid.csv')
news_df['title'] = news_df.apply(lambda row: fixup(row['title'], title=True), axis=1)
news_df['text'] = news_df.apply(lambda row: fixup(row['text'], title=False), axis=1)
news_df['text'] = news_df.apply(lambda row: concat_text_title(row), axis=1)
del news_df['title']
news_df.columns = ['index', 'text']
news_df.to_json('/media/discoD/Mestrado/FASAM/df_valid.jsonl', orient='records', lines=True)
news_df

      index                                               text
0         0  Vitrine de Dilma, Pronatec terá orçamento 65% ...
1         1  Por direitos autorais e publicidade, 'youtuber...
2         2  Rótulos de alimentos terão que alertar sobre l...
3         3  Sociedade britânica de compositores processa S...
4         4  Por Fies, aluna madruga na porta da FMU, mas s...
5         5  Cientistas aguardam nascimento raro de 'dragõe...
6         6  Aplicativo mostra quem está no mesmo voo que v...
7         7  Pesquisas indicam que sono na direção pode ser...
8         8  Brasil lançará missão à Lua até 2020 para estu...
9         9  Cientistas testam vacina contra colesterol e d...
10       10  Farol da Torre Eiffel é desligado para manuten...
11       11  Finalistas do Empreendedor Social terão mentor...
12       12  Eventos marcam comemorações do aniversário de ...
13       13  Folha realiza fórum sobre saúde em tempo de re...
14       14  Por que o 'MasterChef' bateu recordes no Twitt...
15       15  Complexo gastronômico é inaugurado no Recife; ...
16       16  Empresa de presidente do Twitter, Square vai e...
17       17  Lojas e restaurantes testemunham as transforma...
18       18  Fotógrafo registra cânions gaúchos em preto e ...
19       19  Fórum discute inclusão teatral com foco em pro...
20       20  Artista cria em meio ao inferno da favela: 'Co...
21       21  Casal fotografa cenas e paisagens pelo mundo q...
22       22  Fóssil de mandíbula leva à descoberta de bicho...
23       23  Food truck do Mocotó venderá dadinhos de tapio...
24       24  Cientistas comparam ondas cerebrais e algoritm...
25       25  Música mais antiga criada por computador é res...
26       26  Lua de Júpiter vira aposta de cientistas na bu...
27       27  Projeto transforma quarto em área multiúso e t...
28       28  Especialistas estimam em US$ 3 tri transição p...
29       29  Área de reserva para mineração é igual a 4 ano...
...     ...                                                ...
4221   4221  Fenômeno El Niño de 2015 deve ser um dos mais ...
4222   4222  Mensageiro Sideral: Treinamento em jornalismo ...
4223   4223  Pirituba concentra condomínios gigantescos apó...
4224   4224  Carreira de direito ganha mais fama e interess...
4225   4225  Um reconhecimento à causa. O bom de ser reconh...
4226   4226  Refazer provas antigas do Enem pode ajudar na ...
4227   4227  Negócios sociais voltados à primeira infância ...
4228   4228  Carros que chegam em 2017 valorizam espaço int...
4229   4229  Proposta pode acabar com despacho gratuito de ...
4230   4230  Cai para 57 o número de escolas ocupadas em Sã...
4231   4231  Brasileiro é eleito melhor jogador de videogam...
4232   4232  Em um ano na Microsoft, executivo mudou jeito ...
4233   4233  Artemisia seleciona negócios de impacto para p...
4234   4234  Após reclamações, LinkedIn diminui número de e...
4235   4235  Fumar no inverno é pior para a saúde?. Sou fum...
4236   4236  Consumo de cereais integrais pode aumentar lon...
4237   4237  Próxima do metrô, Vila Guilherme cresce ao lad...
4238   4238  Microsoft vai abandonar marca Internet Explore...
4239   4239  OMS comemora grandes avanços na luta contra do...
4240   4240  Modelo de financiamento estudantil também é de...
4241   4241  Queda na cotação do euro estimula compra da mo...
4242   4242  Governo promete pagar a professores meses desc...
4243   4243  Astrônomos da USP tiram dinheiro do próprio bo...
4244   4244  Venda de PCs despencou 38% no segundo trimestr...
4245   4245  Azul do mar se encontra com paisagem do desert...
4246   4246  Barbie grava conversa e 'vira' espiã da Aleman...
4247   4247  Crescimento no serviço de nuvem não evita qued...
4248   4248  O revolucionário projeto de viagem interestela...
4249   4249  Chef suíço que se suicidou pode ter sido vítim...
4250   4250  Humoristas satirizam comportamento de brasilei...

[4251 rows x 2 columns]

In [35]:
news_df.groupby('label').describe()

                    text         \
                   count unique
label
ambiente             317    317
ciencia              849    847
comida               544    544
educacao            1369   1369
empreendedorsocial   557    557
equilibrioesaude     858    858
sobretudo            703    703
tec                 1452   1451
turismo             1245   1245


                                                                  top freq
label
ambiente            Há microplásticos na água da torneira de todo ...    1
ciencia             São as águas de Marte fechando o verão. É prom...    3
comida              Alex Atala lança serviço de bufês para casamen...    1
educacao            Por desocupação, juiz do DF libera isolar alun...    1
empreendedorsocial  Brasil busca primeira colocação na olimpíada d...    1
equilibrioesaude    Provas científicas não conseguem mudar mentali...    1
sobretudo           Honda Fit 2018 vem maior e mais equipado. DE S...    1
tec                 Site diz que selfies já mataram mais que tubar...    2
turismo             Fotógrafo registra casas de Cabo Polonio, no U...    1

In [7]:
# Categoriza o target "category" -> [0,..., 1] (output: y)
Y_classes = pd.get_dummies(news_df['category']).columns
Y_classes

Index(['ambiente', 'ciencia', 'comida', 'educacao', 'empreendedorsocial',
       'equilibrioesaude', 'sobretudo', 'tec', 'turismo'],
      dtype='object')

In [8]:
Y         = pd.get_dummies(news_df['category']).values
Y

array([[0, 0, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [24]:
pd.concat([dataframe['text'], functions_full_df]).drop_duplicates(keep=False).to_csv('../dataset/functions_classifier/functions_diff.csv', header=None, index=None)

In [27]:
functions_df = pd.read_csv('../dataset/functions_classifier/funcoes.csv', header=None)
functions_df

     0                                                1
0    0                                              RÉU
1    1                                   Rel . Ministro
2    0                             estudante de Direito
3    0         Secretário da Fazenda do Estado do Ceará
4    0                                        RECORRIDO
5    1                                Juíza do Trabalho
6    0                                         advogado
7    1                                         MINISTRO
8    0                         Secretário de Audiências
9    1                                    Desembargador
10   0                                         ADVOGADO
11   0                               sócio do executado
12   1                            Desembargador Relator
13   0                                       reclamados
14   0                 segunda testemunha do reclamante
15   0                      1ª testemunha do reclamante
16   0                                        ADVOGADOS
17   0                                       IMPETRANTE
18   0                             Procuradora Regional
19   1                                            Min .
20   1                                      Min . Rel .
21   1                                          relator
22   0                                 Parte reclamante
23   1                               JUÍZA SENTENCIANTE
24   0                                        exequente
25   0                                       reconvindo
26   1                        Desembargador do Trabalho
27   0                preposto do ( a ) recorrido ( a )
28   0                                  recorrido ( a )
29   0                preposto do ( a ) recorrido ( s )
..  ..                                              ...
142  1                Juíza titular de Vara do Trabalho
143  0                                       Calculista
144  1                                    Revisor ( a )
145  1                                 Juíza Substituta
146  0                                            Autor
147  0                                              Réu
148  1                                      rel . des .
149  0                                         preposta
150  1                            Relator DESEMBARGADOR
151  0              Secretário da 1ª Turma - Substituto
152  0                                    1a. reclamada
153  0                                  ( 2a. reclamada
154  1                      Terceiro Magistrado Votante
155  1                               Juíza Sentenciante
156  1                                RELATOR DESIGNADO
157  1                                Relator Designado
158  1                                      Des ( a ) .
159  1                       Redator designado Ministro
160  0  1ª TESTEMUNHA APRESENTADA PELO ( A ) RECLAMANTE
161  1                                 relator Ministro
162  1                                relatora Ministra
163  0                  Segunda testemunha da reclamada
164  0                preposto do ( a ) executado ( a )
165  1                          Revisora Desembargadora
166  1                              Revisora e Redatora
167  1                                         Revisora
168  1                Juíza Titular de Vara do Trabalho
169  1                                          REDATOR
170  0          ex-ministro do Trabalho e ex-presidente
171  1                                  juíza convocada

[172 rows x 2 columns]

In [25]:
functions_diff_df = pd.read_csv('../dataset/functions_classifier/functions_diff.csv', header=None)
functions_diff_df

     0                                   1
0    0                           EXEQÜENTE
1    0                           EXECUTADO
2    1                               Juíza
3    0                          RECORRENTE
4    1                             RELATOR
5    1                                Juiz
6    1                   Relatora Ministra
7    1                         Rel . Min .
8    1               Relator ( a ) : Min .
9    1                         Rel . Des .
10   1                          Relª Juíza
11   1                          Rel . Juiz
12   1                    Relator Ministro
13   1                   Relª Juíza Conv .
14   1                presidente / relator
15   1                      Desembargadora
16   0    Procuradora Regional do Trabalho
17   1        Juíza do Trabalho Substituta
18   1                    Juiz do Trabalho
19   0                          RECLAMANTE
20   0                           RECLAMADO
21   0                          reclamante
22   0                             patrono
23   0   preposto do ( a ) reclamado ( a )
24   0                      advogado ( a )
25   0                 reclamado principal
26   0                               AUTOR
27   1                   JUÍZA DO TRABALHO
28   0               preposto do executado
29   0       Secretário ( a ) de Audiência
..  ..                                 ...
180  0                          Recorridos
181  0                             ESPÓLIO
182  0                           Recorrido
183  1                    Redator Ministro
184  1                   Juiz SENTENCIANTE
185  1                  Relator , Ministro
186  1                      Relatora Juíza
187  1               Revisor Desembargador
188  1                               Rel .
189  1                         Relator DES
190  1                       Relator Des .
191  1    Magistrados Federais do Trabalho
192  1               Desembargador Revisor
193  0                             jurista
194  1                 Rel . Des . Relator
195  1                       Relª . Desª .
196  1                            relatora
197  1  Desembargadora Federal do Trabalho
198  0                     processualistas
199  0                      preposto ( a )
200  1                Rel . Juiz Convocado
201  0                          empregados
202  0                           empregado
203  1                 Rel . Desembargador
204  1                         Rel . Min .
205  1                       RELATOR Des .
206  0                            juristas
207  0                          economista
208  1                    Ministro Relator
209  1                            ministra

[210 rows x 2 columns]

In [35]:
all_functions_df = pd.concat([functions_diff_df, functions_df]).drop_duplicates(keep=False)
all_functions_df.columns = ['label', 'text']
# all_functions_df.rename(columns={0:'label', 1:'text'})
all_functions_df

     label                                             text
0        0                                        EXEQÜENTE
1        0                                        EXECUTADO
2        1                                            Juíza
3        0                                       RECORRENTE
4        1                                          RELATOR
5        1                                             Juiz
6        1                                Relatora Ministra
8        1                            Relator ( a ) : Min .
9        1                                      Rel . Des .
10       1                                       Relª Juíza
11       1                                       Rel . Juiz
12       1                                 Relator Ministro
13       1                                Relª Juíza Conv .
14       1                             presidente / relator
15       1                                   Desembargadora
16       0                 Procuradora Regional do Trabalho
17       1                     Juíza do Trabalho Substituta
18       1                                 Juiz do Trabalho
19       0                                       RECLAMANTE
20       0                                        RECLAMADO
21       0                                       reclamante
22       0                                          patrono
23       0                preposto do ( a ) reclamado ( a )
24       0                                   advogado ( a )
25       0                              reclamado principal
26       0                                            AUTOR
27       1                                JUÍZA DO TRABALHO
28       0                            preposto do executado
29       0                    Secretário ( a ) de Audiência
30       0                                preposta do autor
..     ...                                              ...
142      1                Juíza titular de Vara do Trabalho
143      0                                       Calculista
144      1                                    Revisor ( a )
145      1                                 Juíza Substituta
146      0                                            Autor
147      0                                              Réu
148      1                                      rel . des .
149      0                                         preposta
150      1                            Relator DESEMBARGADOR
151      0              Secretário da 1ª Turma - Substituto
152      0                                    1a. reclamada
153      0                                  ( 2a. reclamada
154      1                      Terceiro Magistrado Votante
155      1                               Juíza Sentenciante
156      1                                RELATOR DESIGNADO
157      1                                Relator Designado
158      1                                      Des ( a ) .
159      1                       Redator designado Ministro
160      0  1ª TESTEMUNHA APRESENTADA PELO ( A ) RECLAMANTE
161      1                                 relator Ministro
162      1                                relatora Ministra
163      0                  Segunda testemunha da reclamada
164      0                preposto do ( a ) executado ( a )
165      1                          Revisora Desembargadora
166      1                              Revisora e Redatora
167      1                                         Revisora
168      1                Juíza Titular de Vara do Trabalho
169      1                                          REDATOR
170      0          ex-ministro do Trabalho e ex-presidente
171      1                                  juíza convocada

[380 rows x 2 columns]

In [36]:
all_functions_df.groupby(['label']).describe()

       text
      count unique                   top freq
label
0       220    220  TERCEIRO INTERESSADO    1
1       160    160       Vice-Presidente    1

In [44]:
trn_df,val_df = train_test_split(all_functions_df, test_size=0.3)

In [45]:
trn_df.groupby(['label']).describe()

       text
      count unique                               top freq
label
0       164    164  segunda testemunha do reclamante    1
1       102    102                     Relª . Desª .    1

In [46]:
val_df.groupby(['label']).describe()

       text
      count unique              top freq
label
0        56     56       RECLAMANTE    1
1        58     58  Vice-Presidente    1

In [47]:
val_df, test_df = train_test_split(val_df, test_size=0.5)

In [48]:
val_df.groupby(['label']).describe()

       text
      count unique                     top freq
label
0        30     30               EXEQÜENTE    1
1        27     27  JUIZ ( A ) DO TRABALHO    1

In [49]:
test_df.groupby(['label']).describe()

       text
      count unique          top freq
label
0        26     26   RECLAMANTE    1
1        31     31  Des ( a ) .    1

In [51]:
trn_df.to_json('../dataset/functions_classifier/train.jsonl', orient='records', lines=True)
val_df.to_json('../dataset/functions_classifier/dev.jsonl', orient='records', lines=True)
test_df.to_json('../dataset/functions_classifier/test.jsonl', orient='records', lines=True)